$defs:
  Input:
    description: Specify (transformations of) the input layer.
    properties:
      input_id:
        title: Input Id
        type: string
      transform:
        anyOf:
        - type: object
        - type: 'null'
        default: null
        title: Transform
    required:
    - input_id
    title: Input
    type: object
  Layer:
    description: Specify layers.
    properties:
      layer_id:
        title: Layer Id
        type: string
      layer_type:
        title: Layer Type
        type: string
      args:
        anyOf:
        - type: object
        - type: 'null'
        default: null
        title: Args
    required:
    - layer_id
    - layer_type
    title: Layer
    type: object
  MLModel:
    description: 'An easy-to-use format to specify simple deep ML models.


      There is a function to export this to a PyTorch module, or to YAML.'
    properties:
      mlmodel_id:
        title: Mlmodel Id
        type: string
      inputs:
        items:
          $ref: '#/$defs/Input'
        title: Inputs
        type: array
      layers:
        items:
          $ref: '#/$defs/Layer'
        title: Layers
        type: array
      forward:
        items:
          $ref: '#/$defs/Node'
        title: Forward
        type: array
    required:
    - mlmodel_id
    - inputs
    - layers
    - forward
    title: MLModel
    type: object
  Node:
    description: 'A node of the computational graph.


      e.g. a node in the forward call of a PyTorch model.

      Ref: https://pytorch.org/docs/stable/fx.html#torch.fx.Node'
    properties:
      name:
        title: Name
        type: string
      op:
        title: Op
        type: string
      target:
        title: Target
        type: string
      args:
        anyOf:
        - items: {}
          type: array
        - type: 'null'
        default: null
        title: Args
      kwargs:
        anyOf:
        - type: object
        - type: 'null'
        default: null
        title: Kwargs
    required:
    - name
    - op
    - target
    title: Node
    type: object
description: Specify all ML models of your hybrid model.
properties:
  models:
    items:
      $ref: '#/$defs/MLModel'
    title: Models
    type: array
required:
- models
title: MLModels
type: object
